workflows:
  my-workflow:
    name: Windows Workflow
    instance_type: windows_x2 # Menggunakan instance windows x2
    scripts:
      - name: Cek Ping ke Google
        script: |
          # Perintah ping di Windows
          ping -n 4 google.com
      - name: Cek Ping ke Server Tujuan (Contoh)
        script: |
          # Ganti dengan IP atau domain server tujuan Anda
          ping -t google.com
    # ...
